#!/bin/sh
#
# Copyright (c) 2018 Sean Davies <sean@city17.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

die()
{
	echo "$1" 1>&2
	exit 1
}

lookup_spf_record()
{
	local _domain=$1 _i
	[ -n "${_domain}" ] || die "usage: ${0##*/} domain"

	dig +short ${_domain} txt \
	  | grep v=spf1 \
	  | tr ' ' '\n' \
	  | sed 's/[+"]//g' \
 	  | while read -r _i; do
		case ${_i} in
		ip[46]:*)   echo ${_i#*:} ;;
		include:*)  lookup_spf_record ${_i#*:} ;;
		redirect=*) lookup_spf_record ${_i#*=} ;;
		a|mx)       lookup_${_i}_record ${_domain} ;;
		a:*|mx:*)   lookup_${_i%:*}_record ${_i#*:} ;;
		esac
	done
}

lookup_a_record()
{
	local _domain=$1
	[ -n "${_domain}" ] || return

	dig +short ${_domain} a | grep -v '\.$'
}

lookup_mx_record()
{
	local _domain=$1 _i
	[ -n "${_domain}" ] || return

	dig +short ${_domain} mx \
	  | sed 's#.* \(.*\).$#\1#' \
	  | while read -r _i; do
		[ -n "${_i}" ] && lookup_a_record ${_i}
	done
}

command -v dig >/dev/null || die "${0##*/}: dig: command not found"
lookup_spf_record $1
